export const CIRCUIT_META = {
  1: { name: "Silverstone Circuit", slug: "silverstone-8", lengthKm: 5.891, corners: 18, slogan: "The Home of British Motorsport" },
  2: { name: "Circuit de Monaco", slug: "monaco-6", lengthKm: 3.337, corners: 19, slogan: "The Jewel in the Crown" },
  5: { name: "Circuit de Spa-Francorchamps", slug: "spa-francorchamps-4", lengthKm: 7.004, corners: 19, slogan: "The Rollercoaster in the Ardennes" },
  7: { name: "Autodromo Nazionale di Monza", slug: "monza-7", lengthKm: 5.793, corners: 11, slogan: "The Temple of Speed" },
  11: { name: "Circuit Park Zandvoort", slug: "zandvoort-5", lengthKm: 4.259, corners: 14, slogan: "The Dunes of Speed" },
  23: { name: "Autódromo Hermanos Rodríguez", slug: "mexico-city-3", lengthKm: 4.304, corners: 17, slogan: "The Fiesta in the Stadium" },
  34: { name: "Red Bull Ring", slug: "spielberg-3", lengthKm: 4.318, corners: 10, slogan: "The Alpine Arena" },
  37: { name: "Autódromo José Carlos Pace", slug: "interlagos-2", lengthKm: 4.309, corners: 15, slogan: "The Crucible of Champions" },
  44: { name: "Circuit Gilles Villeneuve", slug: "montreal-6", lengthKm: 4.361, corners: 14, slogan: "The Island Wall of Champions" },
  52: { name: "Hungaroring", slug: "hungaroring-3", lengthKm: 4.381, corners: 14, slogan: "Monaco Without Walls" },
  53: { name: "Suzuka Circuit", slug: "suzuka-2", lengthKm: 5.807, corners: 18, slogan: "The Ultimate Driver's Test" },
  56: { name: "Circuit de Barcelona-Catalunya", slug: "catalunya-6", lengthKm: 4.657, corners: 14, slogan: "The Ultimate Testing Ground" },
  59: { name: "Albert Park Grand Prix Circuit", slug: "melbourne-2", lengthKm: 5.278, corners: 14, slogan: "The Pride of Down Under" },
  61: { name: "Bahrain International Circuit", slug: "bahrain-1", lengthKm: 5.412, corners: 15, slogan: "The Desert Under Lights" },
  62: { name: "Shanghai International Circuit", slug: "shanghai-1", lengthKm: 5.451, corners: 16, slogan: "The Majestic 'Shang' Layout" },
  65: { name: "Marina Bay Street Circuit", slug: "marina-bay-4", lengthKm: 4.940, corners: 19, slogan: "The Concrete Jungle" },
  66: { name: "Yas Marina Circuit", slug: "yas-marina-2", lengthKm: 5.281, corners: 16, slogan: "The Twilight Finale" },
  69: { name: "Circuit of the Americas", slug: "austin-1", lengthKm: 5.513, corners: 20, slogan: "The Lone Star Track" },
  71: { name: "Baku City Circuit", slug: "baku-1", lengthKm: 6.003, corners: 20, slogan: "The Street Fight in the East" },
  74: { name: "Losail International Circuit", slug: "lusail-1", lengthKm: 5.419, corners: 16, slogan: "The Night-Lit Desert Flyer" },
  75: { name: "Jeddah Corniche Circuit", slug: "jeddah-1", lengthKm: 6.174, corners: 27, slogan: "The World's Fastest Street Track" },
  76: { name: "Miami International Autodrome", slug: "miami-1", lengthKm: 5.412, corners: 19, slogan: "The Sunshine State Showcase" },
  77: { name: "Las Vegas Strip Street Circuit", slug: "las-vegas-1", lengthKm: 6.201, corners: 17, slogan: "The Neon Speed Ring" },
  79: { name: "Madring", slug: "madring-1", lengthKm: 5.474, corners: 20, slogan: "The Future Spanish Grid" },
};